### ISSUE TITLE
[EPIC]: TODO

### ISSUE THREAD

**Issue by alexzhelyapov1** [Naminar/VM#6]
- [ ] Do not use vector in frames
- [ ] Fix workflow, in interpretator::Call -> call Run new bytecode.
- [ ] Remove raw bytecode, do `instr_<name>` structures.
- [ ] Removed ptr from interpretator
- [ ] Create builder
- [ ] Use only int64_t
- [ ] Remove return_code, use only return_value
